'''
Created on Apr 14, 2018

@author: Miguel
'''

ATTR_DISK_AVAILABLE = []
ATTR_SHOW_AVAILABLE = ["bm2"]
ATTR_DEPARTMENT_AVAILABLE = []
ATTR_ASSET_AVAILABLE = []
ATTR_TASK_AVAILABLE = []
ATTR_DETAILS_AVAILABLE = []
ATTR_MAIN_AVAILABLE = []
ATTR_FOLDER_AVAILABLE = []
ATTR_FILENAME_AVAILABLE = []